# Generated by Django 4.2.3 on 2023-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('ST', 'Santander'), ('IT', 'Itaú')], max_length=2),
        ),
    ]
